---------------------------------------------------------------------------------
-- Address decode logic for IPbus fabric.
--
-- This file has been AUTOGENERATED from the address table - do not
-- hand edit.
--
-- We assume the synthesis tool is clever enough to recognise
-- exclusive conditions in the if statement.
---------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package ipbus_decode_address_table is

-- START automatically generated VHDL (Wed Mar 11 02:05:10 2026)
  constant IPBUS_SEL_WIDTH: positive := 3;
-- END automatically generated VHDL

  subtype ipbus_sel_t is std_logic_vector(IPBUS_SEL_WIDTH - 1 downto 0);
  function ipbus_sel_address_table(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t;

-- START automatically generated VHDL (Wed Mar 11 02:05:10 2026)
  constant N_SLV_CTRL_REG: integer := 0;
  constant N_SLV_RAM: integer := 1;
  constant N_SLV_LOG_RAM_0: integer := 2;
  constant N_SLV_LOG_RAM_1: integer := 3;
  constant N_SLAVES: integer := 4;
-- END automatically generated VHDL

end ipbus_decode_address_table;

package body ipbus_decode_address_table is

  function ipbus_sel_address_table(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t is
    variable sel: ipbus_sel_t;
  begin

-- START automatically generated VHDL (Wed Mar 11 02:05:10 2026)
    if    std_match(addr, "-------------000----------------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_CTRL_REG, IPBUS_SEL_WIDTH)); -- ctrl_reg / base 0x00000000 / mask 0x00070000
    elsif std_match(addr, "-------------010----------------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_RAM, IPBUS_SEL_WIDTH)); -- ram / base 0x00020000 / mask 0x00070000
    elsif std_match(addr, "-------------011----------------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_LOG_RAM_0, IPBUS_SEL_WIDTH)); -- log_ram_0 / base 0x00030000 / mask 0x00070000
    elsif std_match(addr, "-------------100----------------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_LOG_RAM_1, IPBUS_SEL_WIDTH)); -- log_ram_1 / base 0x00040000 / mask 0x00070000
    else
        sel := ipbus_sel_t(to_unsigned(N_SLAVES, IPBUS_SEL_WIDTH));
    end if;
-- END automatically generated VHDL

    return sel;

  end function ipbus_sel_address_table;

end ipbus_decode_address_table;

---------------------------------------------------------------------------------
